# Generated by Django 4.2.6 on 2024-03-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(db_column='id_metric', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('domain', models.CharField(max_length=50)),
                ('tool', models.TextField()),
                ('key', models.TextField()),
            ],
            options={
                'db_table': 'metrics',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(db_column='id_project', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.TextField()),
                ('last_analysis_sq', models.DateTimeField()),
                ('last_analysis_sm', models.DateTimeField()),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
