# Generated by Django 4.2.11 on 2026-02-19 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id_component', models.AutoField(primary_key=True, serialize=False)),
                ('qualifier', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'components',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id_metric', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('tool', models.CharField(blank=True, max_length=50, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'metrics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('last_analysis_sq', models.DateTimeField(blank=True, null=True)),
                ('last_analysis_sm', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SonarToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sonar_token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectMeasure',
            fields=[
                ('id_pmeasure', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=80, null=True)),
                ('id_metric', models.ForeignKey(db_column='id_metric', on_delete=django.db.models.deletion.DO_NOTHING, to='main.metric')),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, to='main.project')),
            ],
            options={
                'db_table': 'project_measures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComponentMeasure',
            fields=[
                ('id_cmeasure', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=80, null=True)),
                ('id_component', models.ForeignKey(db_column='id_component', on_delete=django.db.models.deletion.DO_NOTHING, to='main.component')),
                ('id_metric', models.ForeignKey(db_column='id_metric', on_delete=django.db.models.deletion.DO_NOTHING, to='main.metric')),
            ],
            options={
                'db_table': 'component_measures',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='component',
            name='id_project',
            field=models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, to='main.project'),
        ),
        migrations.CreateModel(
            name='ClassMeasure',
            fields=[
                ('id_clmeasure', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=600, null=True)),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.DO_NOTHING, to='main.class')),
                ('id_metric', models.ForeignKey(db_column='id_metric', on_delete=django.db.models.deletion.DO_NOTHING, to='main.metric')),
            ],
            options={
                'db_table': 'class_measures',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='class',
            name='id_component',
            field=models.ForeignKey(db_column='id_component', on_delete=django.db.models.deletion.DO_NOTHING, to='main.component'),
        ),
    ]
