# Generated by Django 4.2.11 on 2026-02-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonartoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sonartoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
